### ISSUE TITLE
Cannot initialize an empty layer

### ISSUE THREAD

**Issue by miketahani** [cyrilcherian/Leaflet-Fullcanvas#2]
A quadtree isn't defined for the layer until a setData() call, so the map will bail on adding the layer because this._myQuad doesn't exist. 

Use case is when I want to add data from a streaming source.

Fix is to call L.FullCanvas.setData([]) before adding it to the map, or initialize the quadtree outside setData.

**Comment by cyrilcherian** [comment]
Hi miketahani ,

When you stream the data you can use

//add points to the layer...here slat denotes the latitude and slon denotes the longitude
layer.addData({"slat": -33.3042, "slon": 26.5328});

But yes you need to call setData once before this, so that this._myQuad is initailsed.

Hope it helps!
